DROP TABLE item IF EXISTS;
CREATE TABLE item (
                      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                      name VARCHAR(250),
                      price INTEGER,
                      quantity INTEGER
);
INSERT INTO item(id, name, price, quantity) values (1, 'Item-1', 10, 20);
INSERT INTO item(id, name, price, quantity) values (2, 'Item-2', 5, 10);
INSERT INTO item(id, name, price, quantity) values (3, 'Item-3', 15, 2);